version: '3.8'

services:
  api_gateway:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn services.api_gateway.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis # Задел на будущее
  
  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python services/telegram_bot/main.py
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - api_gateway

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  poetry_cache: 